### ISSUE TITLE
Category Controller - Get Category by Id - “/category/{category_id}”

### ISSUE THREAD

**Issue by simpleprahalad** [simpleprahalad/FoodOrderingApp-Backend#17]
Get Category by Id - “/category/{category_id}”

It should be a GET request.

This endpoint must request the following value from the customer as a path variable:

Category UUID - String

If the category id field is empty, throw “CategoryNotFoundException” with the message code (CNF-001) and message (Category id field should not be empty) and their corresponding HTTP status.

If there are no categories available by the id provided, throw “CategoryNotFoundException” with the message code (CNF-002) and message (No category by this id) and their corresponding HTTP status.

If the category id entered by the customer matches any category in the database, it should retrieve that category with all items within that category and then display the response in a JSON format with the corresponding HTTP status. 

Here is a link to a sample JSON response.

**Comment by mshashank0** [comment]
Merged and working fine. Closing the issue.
