### ISSUE TITLE
Address Controller - Get All Saved Addresses - “/address/customer”

### ISSUE THREAD

**Issue by simpleprahalad** [simpleprahalad/FoodOrderingApp-Backend#7]
Get All Saved Addresses - “/address/customer”

It should be a GET request.

Access to this endpoint requires authentication.

This endpoint must request the access token of the signed in customer in authorization Request Header.

If the access token provided by the customer does not exist in the database, throw “AuthorizationFailedException” with the message code (ATHR-001) and message (Customer is not Logged in.) along with the corresponding HTTP status.

If the access token provided by the customer exists in the database, but the customer has already logged out, throw “AuthorizationFailedException” with the message code (ATHR-002) and message (Customer is logged out. Log in again to access this endpoint.) along with the corresponding HTTP status.

If the access token provided by the customer exists in the database, but the session has expired, throw “AuthorizationFailedException” with the message code (ATHR-003) and message (Your session is expired. Log in again to access this endpoint.) along with the corresponding HTTP status.

Else, return the list of saved address in descending order of their saved time in the Json response with the corresponding HTTP status.

Here is the link to a sample JSON response.

**Comment by ahans30** [comment]
Enhancement PR #48 approved and merged into dev. Closing issue.
